# Generated by Django 4.2 on 2023-04-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_profile_address_alter_profile_first_name_and_more'),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cart',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.profile', verbose_name='Profile'),
        ),
    ]
